[package]
name = "libfsntfs-sys"
version = "0.1.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"
links = "libfsntfs"

[dependencies]
chrono = "0.4.6"

[build-dependencies]
autotools = "0.2"

[[example]]
name = "file_attributes"
path = "examples/file_attributes.rs"