[package]
name = "libfsntfs-sys"
version = "0.1.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"
links = "libfsntfs"

[dependencies]
chrono = "0.4.6"
log = "*"
failure = "*"

[dev-dependencies]
env_logger = "*"
lazy_static = "*"

[[example]]
name = "file_attributes"
path = "examples/file_attributes.rs"