coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project: true
    patch: true
    changes: false
  ignore:
    - "libcdata/*"
    - "libcerror/*"
    - "libcfile/*"
    - "libclocale/*"
    - "libcnotify/*"
    - "libcpath/*"
    - "libcsplit/*"
    - "libcthreads/*"
    - "libuna/*"
    - "tests/*"
