[package]
name = "libbfio-rs"
version = "0.1.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

[dependencies]
libbfio-sys = {path = "../libbfio-sys"}
libyal-rs-common = {path = "../common"}
chrono = "0.4.6"
time = "0.1.42"
log = "0.4.6"
failure = "0.1.5"

[features]

default = []

# Use when building static bindings
# it's possible to define LIBBFIO_STATIC_LIBPATH to build against local checkout of the library.
static_link = ["libbfio-sys/static_link"]